# Generated by Django 3.2.8 on 2021-10-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('score', models.CharField(blank=True, choices=[('1', '1 of 10'), ('2', '2 of 10'), ('3', '3 of 10'), ('4', '4 of 10'), ('5', '5 of 10'), ('6', '6 of 10'), ('7', '7 of 10'), ('8', '8 of 10'), ('9', '9 of 10'), ('10', '10 of 10')], default='10', help_text='Score', max_length=2)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_api.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_api.album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_api.albumreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('album_review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_api.albumreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='band_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_api.band'),
        ),
    ]
